from graphene import ObjectType, String, Boolean, ID, Field, Int, Float

class Source(ObjectType):
    author = String()
    author_flair_background_color = String()
    author_flair_type = String()
    body = String()
    can_gild = Boolean()
    collapsed = Boolean()
    collapsed_reason = String()
    created_utc = Int()
    link_id = Int()
    mod_note = String()
    mod_reason_by = String()
    mod_reason_title = String()
    no_follow = Boolean()
    parent_id = Int()
    permalink = String()
    removal_reason = String()
    retrieved_on = Int()
    rte_mode = String()
    score = Int()
    send_replies = Boolean()
    stickied = Boolean()
    subreddit = String()
    subreddit_id = Int()
    title = String()

class Hits(ObjectType):
    index = String()
    type = String()
    id = Int()
    score = Float()
    source = Field(Source)
